### list all messages 
GET http://localhost:3000/api/private/v1/friends/1/messages

### create a new messages
POST http://localhost:3000/api/private/v1/friends/1/messages
Content-Type: application/json

{
    "content":"hi there"
}

### get a particular message 
GET http://localhost:3000/api/private/v1/friends/3/messages/5


###create user 
POST http://localhost:3000/auth/api/v1/users/sign-up
Content-Type: application/json

{
    "email": "anam@gmail.com",
    "password": "123456"
}

###authenticate user 
POST http://localhost:3000/auth/api/v1/users/sign-in
Content-Type: application/json

{
    "email": "uddin@gmail.com",
    "password": "123456"
}

###sign out user
POST http://localhost:3000/auth/api/v1/users/sign-out

###who am i
GET http://localhost:3000/auth/api/v1/users/whoami

###get user 
GET http://localhost:3000/auth/api/v1/users/3

###get users 
GET http://localhost:3000/auth/api/v1/users/all

###update user 
PUT http://localhost:3000/auth/api/v1/users/3
Content-Type: application/json

{
    "email": "anam@gmail.com",
    "password":"kjsdflkjslkjsfd"
}

###get user 
DELETE  http://localhost:3000/auth/api/v1/users/5


### set a color 
GET http://localhost:3000/auth/api/v1/users/colors/red

### get a color 
GET http://localhost:3000/auth/api/v1/users/colors

